[2025-02-09T12:50:57.543+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-09T12:50:57.569+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_postgres_tables.extract_postgres_data manual__2025-02-09T12:50:48.644783+00:00 [queued]>
[2025-02-09T12:50:57.580+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_postgres_tables.extract_postgres_data manual__2025-02-09T12:50:48.644783+00:00 [queued]>
[2025-02-09T12:50:57.582+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-09T12:50:57.605+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): extract_postgres_data> on 2025-02-09 12:50:48.644783+00:00
[2025-02-09T12:50:57.616+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=256) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-09T12:50:57.620+0000] {standard_task_runner.py:72} INFO - Started process 259 to run task
[2025-02-09T12:50:57.626+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_postgres_tables', 'extract_postgres_data', 'manual__2025-02-09T12:50:48.644783+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/Extract_DB_data.py', '--cfg-path', '/tmp/tmppjo2e09e']
[2025-02-09T12:50:57.628+0000] {standard_task_runner.py:105} INFO - Job 78: Subtask extract_postgres_data
[2025-02-09T12:50:58.765+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_postgres_tables.extract_postgres_data manual__2025-02-09T12:50:48.644783+00:00 [running]> on host ab1b09830f1d
[2025-02-09T12:50:59.040+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_postgres_tables' AIRFLOW_CTX_TASK_ID='extract_postgres_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-09T12:50:48.644783+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-09T12:50:48.644783+00:00'
[2025-02-09T12:50:59.043+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-09T12:50:59.044+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-09T12:50:59.045+0000] {logging_mixin.py:190} INFO - Current task name:extract_postgres_data state:running start_date:2025-02-09 12:50:57.570293+00:00
[2025-02-09T12:50:59.046+0000] {logging_mixin.py:190} INFO - Dag name:extract_postgres_tables and current dag run status:running
[2025-02-09T12:50:59.047+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-09T12:50:59.048+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-09T12:50:59.050+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/meltano/meltano_project/transform/extract_data_db.py']
[2025-02-09T12:50:59.077+0000] {subprocess.py:99} INFO - Output:
[2025-02-09T12:50:59.552+0000] {subprocess.py:106} INFO - ❌ Erro ao processar categories: connection to server at "localhost" (::1), port 5432 failed: Connection refused
[2025-02-09T12:50:59.554+0000] {subprocess.py:106} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-02-09T12:50:59.556+0000] {subprocess.py:106} INFO - connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
[2025-02-09T12:50:59.557+0000] {subprocess.py:106} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-02-09T12:50:59.559+0000] {subprocess.py:106} INFO - 
[2025-02-09T12:50:59.561+0000] {subprocess.py:106} INFO - ❌ Erro ao processar products: connection to server at "localhost" (::1), port 5432 failed: Connection refused
[2025-02-09T12:50:59.562+0000] {subprocess.py:106} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-02-09T12:50:59.564+0000] {subprocess.py:106} INFO - connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
[2025-02-09T12:50:59.565+0000] {subprocess.py:106} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-02-09T12:50:59.567+0000] {subprocess.py:106} INFO - 
[2025-02-09T12:50:59.583+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-09T12:50:59.655+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-09T12:50:59.657+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extract_postgres_tables, task_id=extract_postgres_data, run_id=manual__2025-02-09T12:50:48.644783+00:00, execution_date=20250209T125048, start_date=20250209T125057, end_date=20250209T125059
[2025-02-09T12:50:59.685+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-09T12:50:59.686+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-09T12:50:59.687+0000] {logging_mixin.py:190} INFO - Dag name:extract_postgres_tables queued_at:2025-02-09 12:50:48.679429+00:00
[2025-02-09T12:50:59.688+0000] {logging_mixin.py:190} INFO - Task hostname:ab1b09830f1d operator:BashOperator
[2025-02-09T12:50:59.754+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-09T12:50:59.804+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-09T12:50:59.808+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
