[2025-02-05T21:20:36.115+0000] {processor.py:186} INFO - Started process (PID=69) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:20:36.118+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:20:36.128+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:20:36.127+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:20:36.191+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:20:36.179+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:20:36.194+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:20:36.259+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.169 seconds
[2025-02-05T21:21:06.367+0000] {processor.py:186} INFO - Started process (PID=134) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:21:06.369+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:21:06.378+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:21:06.377+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:21:06.435+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:21:06.419+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:21:06.439+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:21:06.496+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.149 seconds
[2025-02-05T21:21:36.667+0000] {processor.py:186} INFO - Started process (PID=190) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:21:36.670+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:21:36.674+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:21:36.673+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:21:36.704+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:21:36.697+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:21:36.706+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:21:36.760+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.104 seconds
[2025-02-05T21:22:07.777+0000] {processor.py:186} INFO - Started process (PID=246) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:22:07.779+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:22:07.784+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:22:07.783+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:22:08.397+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:22:08.386+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:22:08.400+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:22:10.105+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 2.338 seconds
[2025-02-05T21:22:40.945+0000] {processor.py:186} INFO - Started process (PID=310) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:22:40.947+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:22:40.952+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:22:40.951+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:22:40.989+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:22:40.981+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:22:40.992+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:22:41.022+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.089 seconds
[2025-02-05T21:23:12.013+0000] {processor.py:186} INFO - Started process (PID=374) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:23:12.015+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:23:12.021+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:23:12.020+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:23:12.054+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:23:12.046+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:23:12.057+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:23:12.088+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.095 seconds
[2025-02-05T21:23:42.928+0000] {processor.py:186} INFO - Started process (PID=438) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:23:42.930+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:23:42.935+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:23:42.934+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:23:42.968+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:23:42.960+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:23:42.971+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:23:43.017+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.099 seconds
[2025-02-05T21:24:13.267+0000] {processor.py:186} INFO - Started process (PID=502) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:24:13.269+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:24:13.274+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:24:13.273+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:24:13.304+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:24:13.297+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:24:13.309+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:24:13.357+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.105 seconds
[2025-02-05T21:24:43.684+0000] {processor.py:186} INFO - Started process (PID=566) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:24:43.686+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:24:43.693+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:24:43.692+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:24:43.734+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:24:43.723+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:24:43.737+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:24:43.780+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.110 seconds
[2025-02-05T21:25:14.513+0000] {processor.py:186} INFO - Started process (PID=630) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:25:14.515+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:25:14.519+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:25:14.519+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:25:14.544+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:25:14.539+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:25:14.547+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:25:14.583+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.079 seconds
[2025-02-05T21:25:44.874+0000] {processor.py:186} INFO - Started process (PID=694) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:25:44.875+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:25:44.880+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:25:44.879+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:25:44.913+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:25:44.905+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:25:44.916+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:25:44.947+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.084 seconds
[2025-02-05T21:26:15.486+0000] {processor.py:186} INFO - Started process (PID=758) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:26:15.488+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:26:15.492+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:26:15.492+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:26:15.526+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:26:15.518+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:26:15.528+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:26:15.562+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.088 seconds
[2025-02-05T21:26:45.634+0000] {processor.py:186} INFO - Started process (PID=822) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:26:45.635+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:26:45.640+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:26:45.640+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:26:45.667+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:26:45.661+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:26:45.669+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:26:45.698+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.074 seconds
[2025-02-05T21:27:16.862+0000] {processor.py:186} INFO - Started process (PID=883) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:27:16.864+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:27:16.869+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:27:16.868+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:27:16.901+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:27:16.893+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:27:16.903+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:27:17.062+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.217 seconds
[2025-02-05T21:27:47.329+0000] {processor.py:186} INFO - Started process (PID=953) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:27:47.330+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:27:47.334+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:27:47.334+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:27:47.355+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:27:47.350+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:27:47.357+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:27:47.383+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.064 seconds
[2025-02-05T21:28:19.295+0000] {processor.py:186} INFO - Started process (PID=1016) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:28:19.297+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:28:19.302+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:28:19.301+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:28:19.334+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:28:19.326+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:28:19.337+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:28:19.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.085 seconds
[2025-02-05T21:28:49.990+0000] {processor.py:186} INFO - Started process (PID=1074) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:28:49.992+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:28:49.997+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:28:49.997+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:28:50.031+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:28:50.024+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:28:50.034+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:28:50.063+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.083 seconds
[2025-02-05T21:29:21.093+0000] {processor.py:186} INFO - Started process (PID=1137) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:29:21.095+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:29:21.099+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:29:21.098+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:29:21.128+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:29:21.121+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:29:21.131+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:29:21.158+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.076 seconds
[2025-02-05T21:29:52.359+0000] {processor.py:186} INFO - Started process (PID=1201) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:29:52.361+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:29:52.365+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:29:52.365+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:29:52.386+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:29:52.382+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:29:52.388+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:29:52.416+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.066 seconds
[2025-02-05T21:30:23.061+0000] {processor.py:186} INFO - Started process (PID=1263) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:30:23.063+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:30:23.067+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:30:23.066+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:30:23.104+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:30:23.095+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:30:23.108+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:30:23.162+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.116 seconds
[2025-02-05T21:30:57.454+0000] {processor.py:186} INFO - Started process (PID=1327) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:30:57.456+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:30:57.464+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:30:57.463+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:30:57.494+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:30:57.487+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:30:58.532+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:30:58.680+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 1.244 seconds
[2025-02-05T21:31:32.606+0000] {processor.py:186} INFO - Started process (PID=1389) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:31:32.609+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:31:32.617+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:31:32.616+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:31:32.644+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:31:32.639+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:31:32.646+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:31:34.563+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 1.973 seconds
[2025-02-05T21:32:17.673+0000] {processor.py:186} INFO - Started process (PID=1452) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:32:17.676+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:32:17.682+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:32:17.681+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:32:17.721+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:32:17.712+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:32:17.724+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:32:17.769+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.138 seconds
[2025-02-05T21:32:48.203+0000] {processor.py:186} INFO - Started process (PID=1513) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:32:48.205+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:32:48.209+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:32:48.208+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:32:48.263+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:32:48.255+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:32:48.266+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:32:48.302+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.110 seconds
[2025-02-05T21:33:18.786+0000] {processor.py:186} INFO - Started process (PID=1577) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:33:18.789+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:33:18.796+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:33:18.795+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:33:18.835+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:33:18.825+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:33:18.838+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:33:18.897+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.126 seconds
[2025-02-05T21:33:49.057+0000] {processor.py:186} INFO - Started process (PID=1641) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:33:49.059+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:33:49.063+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:33:49.063+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:33:49.090+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:33:49.084+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:33:49.093+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:33:49.126+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.082 seconds
[2025-02-05T21:34:19.315+0000] {processor.py:186} INFO - Started process (PID=1704) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:34:19.318+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:34:19.324+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:34:19.323+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:34:19.369+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:34:19.358+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:34:19.374+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:34:19.414+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.113 seconds
[2025-02-05T21:34:50.598+0000] {processor.py:186} INFO - Started process (PID=1766) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:34:50.600+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:34:50.604+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:34:50.604+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:34:50.637+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:34:50.630+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:34:50.640+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:34:50.700+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.114 seconds
[2025-02-05T21:35:21.123+0000] {processor.py:186} INFO - Started process (PID=1820) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:35:21.127+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:35:21.140+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:35:21.139+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:35:21.173+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:35:21.166+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:35:21.176+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:35:21.212+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.111 seconds
[2025-02-05T21:35:51.489+0000] {processor.py:186} INFO - Started process (PID=1887) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:35:51.491+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:35:51.496+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:35:51.495+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:35:51.534+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:35:51.525+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:35:51.537+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:35:51.575+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.097 seconds
[2025-02-05T21:36:21.791+0000] {processor.py:186} INFO - Started process (PID=1948) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:36:21.793+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:36:21.797+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:36:21.796+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:36:21.833+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:36:21.825+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:36:21.836+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:36:21.874+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.095 seconds
[2025-02-05T21:36:52.295+0000] {processor.py:186} INFO - Started process (PID=2011) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:36:52.297+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:36:52.301+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:36:52.301+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:36:52.334+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:36:52.326+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:36:52.337+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:36:52.369+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.086 seconds
[2025-02-05T21:37:23.388+0000] {processor.py:186} INFO - Started process (PID=2073) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:37:23.394+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:37:23.412+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:37:23.406+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:37:23.449+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:37:23.442+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:37:23.454+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:37:23.493+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.130 seconds
[2025-02-05T21:37:53.826+0000] {processor.py:186} INFO - Started process (PID=2133) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:37:53.828+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:37:53.832+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:37:53.831+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:37:53.859+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:37:53.853+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:37:53.862+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:37:53.893+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.077 seconds
[2025-02-05T21:38:24.444+0000] {processor.py:186} INFO - Started process (PID=2196) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:38:24.446+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:38:24.450+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:38:24.450+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:38:24.489+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:38:24.480+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:38:24.492+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:38:24.535+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.103 seconds
[2025-02-05T21:38:54.801+0000] {processor.py:186} INFO - Started process (PID=2259) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:38:54.802+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:38:54.806+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:38:54.805+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:38:54.833+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:38:54.827+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:38:54.835+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:38:54.872+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.081 seconds
[2025-02-05T21:39:25.306+0000] {processor.py:186} INFO - Started process (PID=2322) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:39:25.308+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:39:25.312+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:39:25.312+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:39:25.350+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:39:25.340+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:39:25.353+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:39:25.398+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.103 seconds
[2025-02-05T21:39:55.799+0000] {processor.py:186} INFO - Started process (PID=2386) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:39:55.801+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:39:55.805+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:39:55.805+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:39:55.838+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:39:55.830+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:39:55.840+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:39:55.873+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.085 seconds
[2025-02-05T21:40:25.964+0000] {processor.py:186} INFO - Started process (PID=2447) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:40:25.965+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:40:25.969+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:40:25.969+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:40:25.995+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:40:25.988+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:40:25.997+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:40:26.028+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.075 seconds
[2025-02-05T21:40:36.474+0000] {processor.py:186} INFO - Started process (PID=2493) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:40:36.476+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:40:36.480+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:40:36.479+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:40:36.534+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:40:36.525+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:40:36.537+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:40:36.566+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.101 seconds
[2025-02-05T21:40:36.635+0000] {processor.py:186} INFO - Started process (PID=2494) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T21:40:36.637+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T21:40:36.641+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:40:36.640+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:40:36.675+0000] {logging_mixin.py:190} INFO - [2025-02-05T21:40:36.668+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T21:40:36.678+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T21:40:36.713+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.087 seconds
[2025-02-05T22:19:43.061+0000] {processor.py:186} INFO - Started process (PID=72) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:19:43.303+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:19:43.310+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:19:43.309+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:19:44.242+0000] {processor.py:925} INFO - DAG(s) 'northwind_pipeline' retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:19:50.053+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:19:50.051+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:northwind_pipeline
[2025-02-05T22:19:51.012+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:19:51.012+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:northwind_pipeline
[2025-02-05T22:19:51.035+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:19:51.035+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:northwind_pipeline
[2025-02-05T22:19:51.057+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:19:51.056+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:northwind_pipeline
[2025-02-05T22:19:51.083+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:19:51.082+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:northwind_pipeline
[2025-02-05T22:19:51.119+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:19:51.118+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:northwind_pipeline
[2025-02-05T22:19:51.147+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:19:51.147+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:northwind_pipeline
[2025-02-05T22:19:51.149+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:19:51.149+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-05T22:19:51.187+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:19:51.187+0000] {dag.py:3262} INFO - Creating ORM DAG for northwind_pipeline
[2025-02-05T22:19:51.217+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:19:51.217+0000] {dag.py:4180} INFO - Setting next_dagrun for northwind_pipeline to 2024-01-01 00:00:00+00:00, run_after=2024-01-02 00:00:00+00:00
[2025-02-05T22:19:51.262+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 8.215 seconds
[2025-02-05T22:20:21.846+0000] {processor.py:186} INFO - Started process (PID=137) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:20:21.847+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:20:21.851+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:20:21.850+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:20:21.889+0000] {processor.py:925} INFO - DAG(s) 'northwind_pipeline' retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:20:21.918+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:20:21.917+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-05T22:20:21.952+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:20:21.952+0000] {dag.py:4180} INFO - Setting next_dagrun for northwind_pipeline to 2024-01-01 00:00:00+00:00, run_after=2024-01-02 00:00:00+00:00
[2025-02-05T22:20:21.985+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.148 seconds
[2025-02-05T22:20:52.224+0000] {processor.py:186} INFO - Started process (PID=202) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:20:52.225+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:20:52.229+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:20:52.229+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:20:52.264+0000] {processor.py:925} INFO - DAG(s) 'northwind_pipeline' retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:20:52.292+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:20:52.292+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-05T22:20:52.333+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:20:52.332+0000] {dag.py:4180} INFO - Setting next_dagrun for northwind_pipeline to 2024-01-01 00:00:00+00:00, run_after=2024-01-02 00:00:00+00:00
[2025-02-05T22:20:52.375+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.160 seconds
[2025-02-05T22:21:22.858+0000] {processor.py:186} INFO - Started process (PID=265) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:21:22.861+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:21:22.866+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:21:22.865+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:21:22.901+0000] {processor.py:925} INFO - DAG(s) 'northwind_pipeline' retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:21:22.935+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:21:22.935+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-05T22:21:22.977+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:21:22.976+0000] {dag.py:4180} INFO - Setting next_dagrun for northwind_pipeline to 2024-01-01 00:00:00+00:00, run_after=2024-01-02 00:00:00+00:00
[2025-02-05T22:21:23.015+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.169 seconds
[2025-02-05T22:22:05.296+0000] {processor.py:186} INFO - Started process (PID=326) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:22:05.299+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:22:05.304+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:22:05.303+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:22:05.351+0000] {processor.py:925} INFO - DAG(s) 'northwind_pipeline' retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:22:05.398+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:22:05.398+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-05T22:22:05.458+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:22:05.457+0000] {dag.py:4180} INFO - Setting next_dagrun for northwind_pipeline to 2024-01-01 00:00:00+00:00, run_after=2024-01-02 00:00:00+00:00
[2025-02-05T22:22:05.518+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.243 seconds
[2025-02-05T22:22:35.588+0000] {processor.py:186} INFO - Started process (PID=387) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:22:35.590+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:22:35.594+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:22:35.593+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:22:35.626+0000] {processor.py:925} INFO - DAG(s) 'northwind_pipeline' retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:22:35.659+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:22:35.658+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-05T22:22:35.693+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:22:35.692+0000] {dag.py:4180} INFO - Setting next_dagrun for northwind_pipeline to 2024-01-01 00:00:00+00:00, run_after=2024-01-02 00:00:00+00:00
[2025-02-05T22:22:35.721+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.143 seconds
[2025-02-05T22:23:07.002+0000] {processor.py:186} INFO - Started process (PID=451) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:23:07.015+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:23:07.087+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:23:07.078+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:23:07.474+0000] {processor.py:925} INFO - DAG(s) 'northwind_pipeline' retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:23:07.770+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:23:07.769+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-05T22:23:08.195+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:23:08.195+0000] {dag.py:4180} INFO - Setting next_dagrun for northwind_pipeline to 2024-01-10 00:00:00+00:00, run_after=2024-01-11 00:00:00+00:00
[2025-02-05T22:23:08.366+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 1.570 seconds
[2025-02-05T22:24:27.625+0000] {processor.py:186} INFO - Started process (PID=513) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:24:27.654+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:24:27.673+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:24:27.672+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:24:26.857+0000] {processor.py:925} INFO - DAG(s) 'northwind_pipeline' retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:24:27.005+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:24:27.004+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-05T22:24:27.175+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:24:27.175+0000] {dag.py:4180} INFO - Setting next_dagrun for northwind_pipeline to 2024-01-16 00:00:00+00:00, run_after=2024-01-17 00:00:00+00:00
[2025-02-05T22:24:27.287+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.666 seconds
[2025-02-05T22:24:57.696+0000] {processor.py:186} INFO - Started process (PID=573) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:24:57.699+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:24:57.718+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:24:57.717+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:24:57.841+0000] {processor.py:925} INFO - DAG(s) 'northwind_pipeline' retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:24:58.110+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:24:58.110+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-05T22:24:58.391+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.774 seconds
[2025-02-05T22:25:29.855+0000] {processor.py:186} INFO - Started process (PID=639) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:25:29.867+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:25:29.901+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:25:29.900+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:25:30.010+0000] {processor.py:925} INFO - DAG(s) 'northwind_pipeline' retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:25:30.106+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:25:30.105+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-05T22:25:30.256+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.429 seconds
[2025-02-05T22:26:06.776+0000] {processor.py:186} INFO - Started process (PID=667) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:26:06.785+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:26:06.794+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:26:06.792+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:26:06.998+0000] {processor.py:925} INFO - DAG(s) 'northwind_pipeline' retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:26:07.351+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:26:07.351+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'northwind_pipeline', 'Task Id': 'connect_to_postgres', 'Run Id': 'scheduled__2024-02-02T00:00:00+00:00', 'Hostname': '6340626d4e9b', 'External Executor Id': '8bbeae68-eb49-4fb9-bb40-4ed2313c7860'}
[2025-02-05T22:26:07.620+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-05T22:26:07.635+0000] {logging_mixin.py:190} INFO - Task start:2025-02-05 22:25:35.763326+00:00 end:2025-02-05 22:26:07.416185+00:00 duration:31.652859
[2025-02-05T22:26:07.636+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): connect_to_postgres> dag:<DAG: northwind_pipeline> dagrun:<DagRun northwind_pipeline @ 2024-02-02 00:00:00+00:00: scheduled__2024-02-02T00:00:00+00:00, state:running, queued_at: 2025-02-05 22:25:18.995354+00:00. externally triggered: False>
[2025-02-05T22:26:07.654+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'northwind_pipeline', 'Task Id': 'connect_to_postgres', 'Run Id': 'scheduled__2024-02-02T00:00:00+00:00', 'Hostname': '6340626d4e9b', 'External Executor Id': '8bbeae68-eb49-4fb9-bb40-4ed2313c7860'}
[2025-02-05T22:26:07.657+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:26:07.657+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=northwind_pipeline, task_id=connect_to_postgres, run_id=scheduled__2024-02-02T00:00:00+00:00, execution_date=20240202T000000, start_date=20250205T222535, end_date=20250205T222607
[2025-02-05T22:26:07.818+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:26:07.811+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: northwind_pipeline.connect_to_postgres scheduled__2024-02-02T00:00:00+00:00 [failed]> in state failed
[2025-02-05T22:26:07.943+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:26:07.943+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-05T22:26:08.233+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:26:08.233+0000] {dag.py:4180} INFO - Setting next_dagrun for northwind_pipeline to 2024-02-18 00:00:00+00:00, run_after=2024-02-19 00:00:00+00:00
[2025-02-05T22:26:08.482+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 1.748 seconds
[2025-02-05T22:26:16.739+0000] {processor.py:186} INFO - Started process (PID=688) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:26:16.742+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:26:16.747+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:26:16.746+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:26:16.789+0000] {processor.py:925} INFO - DAG(s) 'northwind_pipeline' retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:26:16.831+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:26:16.831+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'northwind_pipeline', 'Task Id': 'connect_to_postgres', 'Run Id': 'scheduled__2024-02-09T00:00:00+00:00', 'Hostname': '6340626d4e9b', 'External Executor Id': 'add7ab01-6a25-4ef3-bbba-b7f518a7e314'}
[2025-02-05T22:26:16.879+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-05T22:26:16.880+0000] {logging_mixin.py:190} INFO - Task start:2025-02-05 22:25:52.855819+00:00 end:2025-02-05 22:26:16.846683+00:00 duration:23.990864
[2025-02-05T22:26:16.881+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): connect_to_postgres> dag:<DAG: northwind_pipeline> dagrun:<DagRun northwind_pipeline @ 2024-02-09 00:00:00+00:00: scheduled__2024-02-09T00:00:00+00:00, state:running, queued_at: 2025-02-05 22:25:21.617549+00:00. externally triggered: False>
[2025-02-05T22:26:16.882+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'northwind_pipeline', 'Task Id': 'connect_to_postgres', 'Run Id': 'scheduled__2024-02-09T00:00:00+00:00', 'Hostname': '6340626d4e9b', 'External Executor Id': 'add7ab01-6a25-4ef3-bbba-b7f518a7e314'}
[2025-02-05T22:26:16.883+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:26:16.883+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=northwind_pipeline, task_id=connect_to_postgres, run_id=scheduled__2024-02-09T00:00:00+00:00, execution_date=20240209T000000, start_date=20250205T222552, end_date=20250205T222616
[2025-02-05T22:26:16.908+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:26:16.908+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: northwind_pipeline.connect_to_postgres scheduled__2024-02-09T00:00:00+00:00 [failed]> in state failed
[2025-02-05T22:26:16.933+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:26:16.932+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-05T22:26:17.004+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:26:17.004+0000] {dag.py:4180} INFO - Setting next_dagrun for northwind_pipeline to 2024-02-19 00:00:00+00:00, run_after=2024-02-20 00:00:00+00:00
[2025-02-05T22:26:17.039+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.316 seconds
[2025-02-05T22:26:26.280+0000] {processor.py:186} INFO - Started process (PID=729) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:26:26.282+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:26:26.287+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:26:26.286+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:26:26.331+0000] {processor.py:925} INFO - DAG(s) 'northwind_pipeline' retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:26:26.375+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:26:26.374+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-05T22:26:26.428+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:26:26.428+0000] {dag.py:4180} INFO - Setting next_dagrun for northwind_pipeline to 2024-02-21 00:00:00+00:00, run_after=2024-02-22 00:00:00+00:00
[2025-02-05T22:26:26.462+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.192 seconds
[2025-02-05T22:26:57.195+0000] {processor.py:186} INFO - Started process (PID=777) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:26:57.199+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:26:57.206+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:26:57.205+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:26:57.273+0000] {processor.py:925} INFO - DAG(s) 'northwind_pipeline' retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:26:57.343+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:26:57.342+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-05T22:26:57.419+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:26:57.418+0000] {dag.py:4180} INFO - Setting next_dagrun for northwind_pipeline to 2024-02-21 00:00:00+00:00, run_after=2024-02-22 00:00:00+00:00
[2025-02-05T22:26:57.462+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.293 seconds
[2025-02-05T22:27:27.667+0000] {processor.py:186} INFO - Started process (PID=841) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:27:27.668+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:27:27.673+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:27:27.673+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:27:27.718+0000] {processor.py:925} INFO - DAG(s) 'northwind_pipeline' retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:27:27.757+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:27:27.757+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-05T22:27:27.810+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:27:27.809+0000] {dag.py:4180} INFO - Setting next_dagrun for northwind_pipeline to 2024-02-21 00:00:00+00:00, run_after=2024-02-22 00:00:00+00:00
[2025-02-05T22:27:27.851+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.197 seconds
[2025-02-05T22:27:49.644+0000] {processor.py:186} INFO - Started process (PID=888) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:27:49.646+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:27:49.652+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:27:49.652+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:27:49.711+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/Collected_data.py:18 SyntaxWarning: invalid escape sequence '\m'
[2025-02-05T22:27:49.718+0000] {processor.py:925} INFO - DAG(s) 'northwind_pipeline' retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:27:50.055+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:27:50.055+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-05T22:27:50.088+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:27:50.088+0000] {dag.py:4180} INFO - Setting next_dagrun for northwind_pipeline to 2024-02-21 00:00:00+00:00, run_after=2024-02-22 00:00:00+00:00
[2025-02-05T22:27:50.133+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.501 seconds
[2025-02-05T22:28:20.672+0000] {processor.py:186} INFO - Started process (PID=952) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:28:20.674+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:28:20.678+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:28:20.678+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:28:20.717+0000] {processor.py:925} INFO - DAG(s) 'northwind_pipeline' retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:28:20.747+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:28:20.747+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-05T22:28:20.788+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:28:20.787+0000] {dag.py:4180} INFO - Setting next_dagrun for northwind_pipeline to 2024-02-21 00:00:00+00:00, run_after=2024-02-22 00:00:00+00:00
[2025-02-05T22:28:20.820+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.157 seconds
[2025-02-05T22:28:51.182+0000] {processor.py:186} INFO - Started process (PID=1012) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:28:51.184+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:28:51.188+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:28:51.187+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:28:51.235+0000] {processor.py:925} INFO - DAG(s) 'northwind_pipeline' retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:28:51.274+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:28:51.273+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-05T22:28:51.334+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:28:51.334+0000] {dag.py:4180} INFO - Setting next_dagrun for northwind_pipeline to 2024-02-21 00:00:00+00:00, run_after=2024-02-22 00:00:00+00:00
[2025-02-05T22:28:51.367+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.197 seconds
[2025-02-05T22:29:09.905+0000] {processor.py:186} INFO - Started process (PID=1056) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:29:09.907+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:29:09.914+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:29:09.913+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:29:09.978+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/Collected_data.py:18 SyntaxWarning: invalid escape sequence '\m'
[2025-02-05T22:29:09.985+0000] {processor.py:925} INFO - DAG(s) 'northwind_pipeline' retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:29:10.021+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:29:10.021+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-05T22:29:10.066+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:29:10.065+0000] {dag.py:4180} INFO - Setting next_dagrun for northwind_pipeline to 2024-02-21 00:00:00+00:00, run_after=2024-02-22 00:00:00+00:00
[2025-02-05T22:29:10.101+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.209 seconds
[2025-02-05T22:29:10.178+0000] {processor.py:186} INFO - Started process (PID=1057) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:29:10.180+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:29:10.187+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:29:10.186+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:29:10.239+0000] {processor.py:925} INFO - DAG(s) 'northwind_pipeline' retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:29:10.284+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:29:10.283+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-05T22:29:10.345+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:29:10.344+0000] {dag.py:4180} INFO - Setting next_dagrun for northwind_pipeline to 2024-02-21 00:00:00+00:00, run_after=2024-02-22 00:00:00+00:00
[2025-02-05T22:29:10.385+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.219 seconds
[2025-02-05T22:29:10.472+0000] {processor.py:186} INFO - Started process (PID=1058) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:29:10.473+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:29:10.480+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:29:10.479+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:29:10.519+0000] {processor.py:925} INFO - DAG(s) 'northwind_pipeline' retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:29:10.555+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:29:10.554+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-05T22:29:10.600+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:29:10.599+0000] {dag.py:4180} INFO - Setting next_dagrun for northwind_pipeline to 2024-02-21 00:00:00+00:00, run_after=2024-02-22 00:00:00+00:00
[2025-02-05T22:29:10.644+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.183 seconds
[2025-02-05T22:29:40.721+0000] {processor.py:186} INFO - Started process (PID=1122) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:29:40.723+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:29:40.728+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:29:40.727+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:29:40.766+0000] {processor.py:925} INFO - DAG(s) 'northwind_pipeline' retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:29:40.800+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:29:40.799+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-05T22:29:40.844+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:29:40.843+0000] {dag.py:4180} INFO - Setting next_dagrun for northwind_pipeline to 2024-02-21 00:00:00+00:00, run_after=2024-02-22 00:00:00+00:00
[2025-02-05T22:29:40.876+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.166 seconds
[2025-02-05T22:30:11.495+0000] {processor.py:186} INFO - Started process (PID=1190) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:30:11.501+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:30:11.516+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:30:11.514+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:30:11.595+0000] {processor.py:925} INFO - DAG(s) 'northwind_pipeline' retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:30:11.702+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:30:11.702+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-05T22:30:11.832+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:30:11.831+0000] {dag.py:4180} INFO - Setting next_dagrun for northwind_pipeline to 2024-02-23 00:00:00+00:00, run_after=2024-02-24 00:00:00+00:00
[2025-02-05T22:30:11.967+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.494 seconds
[2025-02-05T22:30:58.096+0000] {processor.py:186} INFO - Started process (PID=1244) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:30:58.098+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:30:58.104+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:30:58.103+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:30:58.216+0000] {processor.py:925} INFO - DAG(s) 'northwind_pipeline' retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:30:59.002+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:30:59.001+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-05T22:30:59.109+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:30:59.108+0000] {dag.py:4180} INFO - Setting next_dagrun for northwind_pipeline to 2024-03-07 00:00:00+00:00, run_after=2024-03-08 00:00:00+00:00
[2025-02-05T22:30:59.170+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 1.123 seconds
[2025-02-05T22:31:30.012+0000] {processor.py:186} INFO - Started process (PID=1307) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:31:30.014+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:31:30.018+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:31:30.017+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:31:30.053+0000] {processor.py:925} INFO - DAG(s) 'northwind_pipeline' retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:31:30.084+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:31:30.084+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-05T22:31:30.123+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:31:30.123+0000] {dag.py:4180} INFO - Setting next_dagrun for northwind_pipeline to 2024-03-17 00:00:00+00:00, run_after=2024-03-18 00:00:00+00:00
[2025-02-05T22:31:30.161+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.158 seconds
[2025-02-05T22:35:53.205+0000] {processor.py:186} INFO - Started process (PID=1322) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:35:53.208+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:35:52.401+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:35:52.400+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:35:52.770+0000] {processor.py:925} INFO - DAG(s) 'northwind_pipeline' retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:36:04.653+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:36:04.651+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-05T22:36:05.473+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 13.153 seconds
[2025-02-05T22:36:44.978+0000] {processor.py:186} INFO - Started process (PID=1389) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:36:44.981+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:36:44.983+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:36:44.983+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:36:45.043+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:36:45.032+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T22:36:45.046+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:36:45.081+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.112 seconds
[2025-02-05T22:37:21.618+0000] {processor.py:186} INFO - Started process (PID=1438) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:37:21.620+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:37:21.622+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:37:21.621+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:37:21.651+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:37:21.644+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T22:37:21.653+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:37:21.686+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.078 seconds
[2025-02-05T22:37:52.063+0000] {processor.py:186} INFO - Started process (PID=1501) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:37:52.065+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:37:52.066+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:37:52.066+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:37:52.091+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:37:52.086+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T22:37:52.094+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:37:52.129+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.076 seconds
[2025-02-05T22:37:54.392+0000] {processor.py:186} INFO - Started process (PID=1514) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:37:54.394+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:37:54.397+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:37:54.397+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:37:54.445+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:37:54.438+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T22:37:54.447+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:37:54.480+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.099 seconds
[2025-02-05T22:37:55.191+0000] {processor.py:186} INFO - Started process (PID=1518) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:37:55.193+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:37:55.196+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:37:55.195+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:37:55.239+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:37:55.231+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T22:37:55.242+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:37:55.276+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.099 seconds
[2025-02-05T22:38:26.524+0000] {processor.py:186} INFO - Started process (PID=1582) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:38:26.526+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:38:26.529+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:38:26.529+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:38:26.568+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:38:26.559+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T22:38:26.572+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:38:26.622+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.109 seconds
[2025-02-05T22:38:57.239+0000] {processor.py:186} INFO - Started process (PID=1649) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:38:57.242+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:38:57.244+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:38:57.243+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:38:57.281+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:38:57.273+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T22:38:57.284+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:38:57.315+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.088 seconds
[2025-02-05T22:39:27.586+0000] {processor.py:186} INFO - Started process (PID=1713) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:39:27.588+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:39:27.591+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:39:27.590+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:39:27.629+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:39:27.620+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T22:39:27.632+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:39:27.668+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.093 seconds
[2025-02-05T22:39:59.922+0000] {processor.py:186} INFO - Started process (PID=1776) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:39:59.925+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:39:59.928+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:39:59.927+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:39:59.958+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:39:59.952+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T22:39:59.961+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:40:00.013+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.109 seconds
[2025-02-05T22:40:30.215+0000] {processor.py:186} INFO - Started process (PID=1839) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:40:30.216+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:40:30.219+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:40:30.219+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:40:30.252+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:40:30.244+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T22:40:30.255+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:40:30.295+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.092 seconds
[2025-02-05T22:41:00.681+0000] {processor.py:186} INFO - Started process (PID=1902) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:41:00.683+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:41:00.686+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:41:00.685+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:41:00.707+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:41:00.702+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T22:41:00.709+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:41:00.738+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.068 seconds
[2025-02-05T22:41:30.848+0000] {processor.py:186} INFO - Started process (PID=1961) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:41:30.850+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:41:30.858+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:41:30.857+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:41:30.907+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:41:30.896+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T22:41:30.911+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:41:30.969+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.140 seconds
[2025-02-05T22:42:02.156+0000] {processor.py:186} INFO - Started process (PID=2020) to work on /opt/airflow/dags/Collected_data.py
[2025-02-05T22:42:02.159+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Collected_data.py for tasks to queue
[2025-02-05T22:42:02.162+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:42:02.162+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:42:02.200+0000] {logging_mixin.py:190} INFO - [2025-02-05T22:42:02.190+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Collected_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Collected_data.py", line 2, in <module>
    from airflow.providers.git.operators.git_sync import GitSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.git'
[2025-02-05T22:42:02.203+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Collected_data.py
[2025-02-05T22:42:02.251+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Collected_data.py took 0.114 seconds
