[2025-02-09T19:04:57.597+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-09T19:04:57.622+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_postgres_and_csv_data.run_load_data_script manual__2025-02-09T19:04:42.774520+00:00 [queued]>
[2025-02-09T19:04:57.635+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_postgres_and_csv_data.run_load_data_script manual__2025-02-09T19:04:42.774520+00:00 [queued]>
[2025-02-09T19:04:57.636+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-09T19:04:56.899+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_load_data_script> on 2025-02-09 19:04:42.774520+00:00
[2025-02-09T19:04:56.911+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=281) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-09T19:04:56.914+0000] {standard_task_runner.py:72} INFO - Started process 283 to run task
[2025-02-09T19:04:56.916+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_postgres_and_csv_data', 'run_load_data_script', 'manual__2025-02-09T19:04:42.774520+00:00', '--job-id', '300', '--raw', '--subdir', 'DAGS_FOLDER/extract_postgres_and_csv_data.py', '--cfg-path', '/tmp/tmpfg7p_a2u']
[2025-02-09T19:04:56.918+0000] {standard_task_runner.py:105} INFO - Job 300: Subtask run_load_data_script
[2025-02-09T19:04:56.997+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_postgres_and_csv_data.run_load_data_script manual__2025-02-09T19:04:42.774520+00:00 [running]> on host 58bc83bc12fd
[2025-02-09T19:04:57.175+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_postgres_and_csv_data' AIRFLOW_CTX_TASK_ID='run_load_data_script' AIRFLOW_CTX_EXECUTION_DATE='2025-02-09T19:04:42.774520+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-09T19:04:42.774520+00:00'
[2025-02-09T19:04:57.179+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-09T19:04:57.179+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-09T19:04:57.180+0000] {logging_mixin.py:190} INFO - Current task name:run_load_data_script state:running start_date:2025-02-09 19:04:57.623311+00:00
[2025-02-09T19:04:57.181+0000] {logging_mixin.py:190} INFO - Dag name:extract_postgres_and_csv_data and current dag run status:running
[2025-02-09T19:04:57.182+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-09T19:04:57.183+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-09T19:04:57.185+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/meltano/meltano_project/load/load_data_csv_for_db.py']
[2025-02-09T19:04:57.210+0000] {subprocess.py:99} INFO - Output:
[2025-02-09T19:05:00.443+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-02-09T19:05:00.445+0000] {subprocess.py:106} INFO -   File "/opt/***/meltano/meltano_project/load/load_data_csv_for_db.py", line 5, in <module>
[2025-02-09T19:05:00.448+0000] {subprocess.py:106} INFO -     import openpyxl
[2025-02-09T19:05:00.450+0000] {subprocess.py:106} INFO - ModuleNotFoundError: No module named 'openpyxl'
[2025-02-09T19:05:00.671+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-02-09T19:05:00.695+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-09T19:05:00.716+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-09T19:05:00.718+0000] {logging_mixin.py:190} INFO - Task start:2025-02-09 19:04:57.623311+00:00 end:2025-02-09 19:05:00.715668+00:00 duration:3.092357
[2025-02-09T19:05:00.719+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): run_load_data_script> dag:<DAG: extract_postgres_and_csv_data> dagrun:<DagRun extract_postgres_and_csv_data @ 2025-02-09 19:04:42.774520+00:00: manual__2025-02-09T19:04:42.774520+00:00, state:running, queued_at: 2025-02-09 19:04:42.790796+00:00. externally triggered: True>
[2025-02-09T19:05:00.720+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2025-02-09T19:05:00.721+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=extract_postgres_and_csv_data, task_id=run_load_data_script, run_id=manual__2025-02-09T19:04:42.774520+00:00, execution_date=20250209T190442, start_date=20250209T190457, end_date=20250209T190500
[2025-02-09T19:05:00.760+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-09T19:05:00.762+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 300 for task run_load_data_script (Bash command failed. The command returned a non-zero exit code 1.; 283)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-09T19:05:00.817+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-09T19:05:00.872+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-09T19:05:00.875+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
