[2025-02-09T14:25:38.740+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-09T14:25:38.763+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load_CSV_to_Postgres.run_load_data_script scheduled__2025-02-08T00:00:00+00:00 [queued]>
[2025-02-09T14:25:38.775+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load_CSV_to_Postgres.run_load_data_script scheduled__2025-02-08T00:00:00+00:00 [queued]>
[2025-02-09T14:25:38.776+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-09T14:25:38.798+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_load_data_script> on 2025-02-08 00:00:00+00:00
[2025-02-09T14:25:38.808+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1255) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-09T14:25:38.811+0000] {standard_task_runner.py:72} INFO - Started process 1257 to run task
[2025-02-09T14:25:38.811+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Load_CSV_to_Postgres', 'run_load_data_script', 'scheduled__2025-02-08T00:00:00+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/Load_CSV_to_Postgres.py', '--cfg-path', '/tmp/tmpne7ag_gf']
[2025-02-09T14:25:38.813+0000] {standard_task_runner.py:105} INFO - Job 97: Subtask run_load_data_script
[2025-02-09T14:25:39.135+0000] {task_command.py:467} INFO - Running <TaskInstance: Load_CSV_to_Postgres.run_load_data_script scheduled__2025-02-08T00:00:00+00:00 [running]> on host 8c410daec8d3
[2025-02-09T14:25:39.253+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Load_CSV_to_Postgres' AIRFLOW_CTX_TASK_ID='run_load_data_script' AIRFLOW_CTX_EXECUTION_DATE='2025-02-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-08T00:00:00+00:00'
[2025-02-09T14:25:39.254+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-09T14:25:39.255+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-09T14:25:39.257+0000] {logging_mixin.py:190} INFO - Current task name:run_load_data_script state:running start_date:2025-02-09 14:25:38.764601+00:00
[2025-02-09T14:25:39.258+0000] {logging_mixin.py:190} INFO - Dag name:Load_CSV_to_Postgres and current dag run status:running
[2025-02-09T14:25:39.259+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-09T14:25:39.261+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Load_CSV_to_Postgres.py", line 11, in run_load_data_script
    subprocess.run(["python", script_path], check=True)
    ^^^^^^^^^^
NameError: name 'subprocess' is not defined. Did you forget to import 'subprocess'
[2025-02-09T14:25:39.299+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-09T14:25:39.300+0000] {logging_mixin.py:190} INFO - Task start:2025-02-09 14:25:38.764601+00:00 end:2025-02-09 14:25:39.299028+00:00 duration:0.534427
[2025-02-09T14:25:39.302+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): run_load_data_script> dag:<DAG: Load_CSV_to_Postgres> dagrun:<DagRun Load_CSV_to_Postgres @ 2025-02-08 00:00:00+00:00: scheduled__2025-02-08T00:00:00+00:00, state:running, queued_at: 2025-02-09 14:25:22.620808+00:00. externally triggered: False>
[2025-02-09T14:25:39.303+0000] {logging_mixin.py:190} INFO - Failure caused by name 'subprocess' is not defined
[2025-02-09T14:25:39.304+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Load_CSV_to_Postgres, task_id=run_load_data_script, run_id=scheduled__2025-02-08T00:00:00+00:00, execution_date=20250208T000000, start_date=20250209T142538, end_date=20250209T142539
[2025-02-09T14:25:39.346+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-09T14:25:39.347+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 97 for task run_load_data_script (name 'subprocess' is not defined; 1257)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Load_CSV_to_Postgres.py", line 11, in run_load_data_script
    subprocess.run(["python", script_path], check=True)
    ^^^^^^^^^^
NameError: name 'subprocess' is not defined. Did you forget to import 'subprocess'
[2025-02-09T14:25:39.439+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-09T14:25:39.935+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-09T14:25:39.939+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
